title:               Violin Diffusion
url:                 https://daewoung.github.io/ViolinDiff-Demo/
baseurl:             https://daewoung.github.io/ViolinDiff-Demo

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Daewoong Kim
  url:               daewoung.github.io
  email:             nueyet@naver.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
